"""add known devices table

Revision ID: 000562d45b30
Revises: 2acaca4106a9
Create Date: 2026-09-07 21:38:05.588519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000562d45b30'
down_revision: Union[str, Sequence[str], None] = '2acaca4106a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('known_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=100), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'fingerprint', name='uq_account_device')
    )
    op.create_index(op.f('ix_known_devices_account_id'), 'known_devices', ['account_id'], unique=False)
    op.create_index(op.f('ix_known_devices_fingerprint'), 'known_devices', ['fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_known_devices_fingerprint'), table_name='known_devices')
    op.drop_index(op.f('ix_known_devices_account_id'), table_name='known_devices')
    op.drop_table('known_devices')
    # ### end Alembic commands ###
