"""add focus areas table

Revision ID: 0c1821a677d5
Revises: 5beda75579c3
Create Date: 2026-09-07 06:08:54.668030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1821a677d5'
down_revision: Union[str, Sequence[str], None] = '5beda75579c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('focus_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'code', name='uq_account_focus_area')
    )
    op.create_index(op.f('ix_focus_areas_account_id'), 'focus_areas', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_focus_areas_account_id'), table_name='focus_areas')
    op.drop_table('focus_areas')
    # ### end Alembic commands ###
