"""add cascade delete to entry engine tables

Revision ID: 2a7e2d3ce106
Revises: 3eea812c571a
Create Date: 2026-09-18 20:17:39.954849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7e2d3ce106'
down_revision: Union[str, Sequence[str], None] = '3eea812c571a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('captured_values_entry_id_fkey'), 'captured_values', type_='foreignkey')
    op.create_foreign_key(None, 'captured_values', 'entries', ['entry_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('entries_account_id_fkey'), 'entries', type_='foreignkey')
    op.create_foreign_key(None, 'entries', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_entry_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'entries', ['entry_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_entry_id_fkey'), 'messages', 'entries', ['entry_id'], ['id'])
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.create_foreign_key(op.f('entries_account_id_fkey'), 'entries', 'accounts', ['account_id'], ['id'])
    op.drop_constraint(None, 'captured_values', type_='foreignkey')
    op.create_foreign_key(op.f('captured_values_entry_id_fkey'), 'captured_values', 'entries', ['entry_id'], ['id'])
    # ### end Alembic commands ###
