"""add work_issues and life_vision to accounts

Revision ID: 3eea812c571a
Revises: 241434c0aff7
Create Date: 2026-09-18 09:39:13.798320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3eea812c571a'
down_revision: Union[str, Sequence[str], None] = '241434c0aff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('work_issues', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('accounts', sa.Column('life_vision', sa.String(length=160), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'life_vision')
    op.drop_column('accounts', 'work_issues')
    # ### end Alembic commands ###
