"""add onboarding fields to accounts

Revision ID: 5beda75579c3
Revises: 4cb1797e5a33
Create Date: 2026-09-07 01:49:02.103096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5beda75579c3'
down_revision: Union[str, Sequence[str], None] = '4cb1797e5a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('consent_version', sa.String(length=20), nullable=True))
    op.add_column('accounts', sa.Column('consent_at', sa.DateTime(), nullable=True))
    op.add_column('accounts', sa.Column('distress_baseline', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('distress_baseline_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'distress_baseline_at')
    op.drop_column('accounts', 'distress_baseline')
    op.drop_column('accounts', 'consent_at')
    op.drop_column('accounts', 'consent_version')
    # ### end Alembic commands ###
